# Tell Spring Boot to always initialize the database with SQL scripts
spring.sql.init.mode=always

# If you use Hibernate/JPA entities, ensure they generate tables BEFORE data.sql runs
spring.jpa.defer-datasource-initialization=true

# Optional: Controls automatic table creation by Hibernate
# Set to 'update' or 'create-drop' depending on your environment needs
spring.jpa.hibernate.ddl-auto=none

## MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/microservices
spring.datasource.username=root
spring.datasource.password=@3375#

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=create-drop